apiVersion: v1
kind: Secret
metadata:
  name: nvd-secrets
  namespace: nvd-system
type: Opaque
data:
  # Ова се "postgres" и "supersecret" енкодирани во Base64 формат
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: c3VwZXJzZWNyZXQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvd-config
  namespace: nvd-system
data:
  POSTGRES_DB: "nvd_db"
  DB_HOST: "nvd-database-svc"
  DB_PORT: "5432"