apiVersion: v1
kind: Service
metadata:
  name: nvd-backend-svc
  namespace: nvd-system
spec:
  selector:
    app: nvd-backend
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvd-backend
  namespace: nvd-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvd-backend
  template:
    metadata:
      labels:
        app: nvd-backend
    spec:
      containers:
        - name: backend
          image: stojkovskiandrej/nvd-backend:3540a300c4eea61e2c62b9bf5c634de6550310da
          ports:
            - containerPort: 5000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: nvd-secrets
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: nvd-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nvd-config
                  key: POSTGRES_DB
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: nvd-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: nvd-config
                  key: DB_PORT